# Project: TestTone
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = TestTone.o
LINKOBJ  = TestTone.o
LIBS     = -L"D:/Programming/Dev-Cpp/MinGW32/lib" -L"D:/Programming/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc lib/NIDAQmx.lib -g3
INCS     = -I"D:/Programming/Dev-Cpp/MinGW32/include" -I"D:/Programming/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"D:/Programming/Dev-Cpp/MinGW32/include" -I"D:/Programming/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = TestTone.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

TestTone.o: TestTone.c
	$(CC) -c TestTone.c -o TestTone.o $(CFLAGS)
